yaml


name: PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: PR Review
        uses: team-telnyx/reviewpr@main
        with:
          telnyx_api_key: ${{ secrets.KEY0197A6D1F4FFB646155526A469D7C9DA_WcHqYJJ3wdovF3Vr1bjy9n }}
          model_name: "meta-llama/Meta-Llama-3.1-8B-Instruct"
